sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t mauricio-mautec/docker-react -f Dockerfile.dev .

script:
  - docker run  -e CI=true mauricio-mautec/docker-react npm run test -- --coverage